services:
  web:
    image: web
    build:
      context: .
      dockerfile: src/Web/Dockerfile

  web.client:
    image: web.client
    build:
      context: .
      dockerfile: src/Web.Client/Dockerfile
