services:
  blazorapp:
    build:
      context: .
      target: final
      dockerfile: src/Web/Dockerfile
    environment:
      - SERVICE_FQDN_BLAZORAPP_8080
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_DETAILEDERRORS=${ASPNETCORE_DETAILEDERRORS:-true}
      - APPLICATION_NAME=${APPLICATION_NAME:-blazor.playground}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS:-http://*:8080}
