services:
  blazorapp:
    build:
      dockerfile: src/Web/Dockerfile
    environment:
      - SERVICE_FQDN_BLAZORAPP_8080
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_DETAILEDERRORS=${ASPNETCORE_DETAILEDERRORS:-true}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS:-http://*:8080}
