name: Build and publish docker image
on:
  push:
    branches:
      - main
  pull_request:

permissions: { }

jobs:
  build:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: docker buildx inspect

#      - name: Checkout repository
#        uses: actions/checkout@11bd5729b4e7ac5b9e6a6ba92a4c8c6f2f7c850c # v4.1.1
#        with:
#          persist-credentials: false
