name: Build and publish docker image
on:
  push:
    branches:
      - main
  pull_request:

permissions: { }

jobs:
  build:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@11bd5729b4e7ac5b9e6a6ba92a4c8c6f2f7c850c # v4.1.1
        with:
          persist-credentials: false
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Web/Dockerfile
          target: final
          platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64
          provenance: mode=max
          push: true
          tags: |
            ${{ github.repository }}:preview
            ${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:preview
            ghcr.io/${{ github.repository }}:${{ github.sha }}
